CREATE UNIQUE INDEX "IDX_CUSTOMERS_PHONE_UK" ON "CUSTOMERS" ("PHONE");

-- Indexes for VEHICLES
CREATE UNIQUE INDEX "IDX_VEHICLES_PK" ON "VEHICLES" ("VEHICLE_ID");

CREATE UNIQUE INDEX "IDX_VEHICLES_REG_NUM_UK" ON "VEHICLES" ("REGISTRATION_NUMBER");
CREATE UNIQUE INDEX "IDX_VEHICLES_VIN_UK" ON "VEHICLES" ("VIN");

CREATE UNIQUE INDEX "IDX_SERVICES_PK" ON "SERVICES" ("SERVICE_ID");

-- Indexes for EMPLOYEES
CREATE UNIQUE INDEX "IDX_EMPLOYEES_PK" ON "EMPLOYEES" ("EMPLOYEE_ID");

CREATE UNIQUE INDEX "IDX_ORDERS_PK" ON "ORDERS" ("ORDER_ID");

-- Indexes for ORDER_DETAILS
CREATE UNIQUE INDEX "IDX_ORDER_DETAILS_PK" ON "ORDER_DETAILS" ("DETAIL_ID");

CREATE UNIQUE INDEX "IDX_SUPPLIERS_PK" ON "SUPPLIERS" ("SUPPLIER_ID");

-- Indexes for INVENTORY
CREATE UNIQUE INDEX "IDX_INVENTORY_PK" ON "INVENTORY" ("PART_ID");

CREATE UNIQUE INDEX "IDX_PARTS_USED_PK" ON "PARTS_USED" ("PART_USED_ID");

-- Indexes for INVOICES
CREATE UNIQUE INDEX "IDX_INVOICES_PK" ON "INVOICES" ("INVOICE_ID");

CREATE UNIQUE INDEX "IDX_WORK_SCHEDULES_PK" ON "WORK_SCHEDULES" ("SCHEDULE_ID");

-- Indexes for REPAIR_HISTORY
CREATE UNIQUE INDEX "IDX_REPAIR_HISTORY_PK" ON "REPAIR_HISTORY" ("HISTORY_ID");

CREATE UNIQUE INDEX "IDX_CUSTOMER_REVIEWS_PK" ON "CUSTOMER_REVIEWS" ("REVIEW_ID");

-- Indexes for PAYMENTS
CREATE UNIQUE INDEX "IDX_PAYMENTS_PK" ON "PAYMENTS" ("PAYMENT_ID");

CREATE UNIQUE INDEX "IDX_EMPLOYEE_ROLES_PK" ON "EMPLOYEE_ROLES" ("ROLE_ID");

-- Indexes for EMPLOYEE_PERMISSIONS
CREATE UNIQUE INDEX "IDX_EMPLOYEE_PERMISSIONS_PK" ON "EMPLOYEE_PERMISSIONS" ("PERMISSION_ID");

CREATE UNIQUE INDEX "IDX_SUPPLY_ORDERS_PK" ON "SUPPLY_ORDERS" ("SUPPLY_ORDER_ID");

-- Indexes for SUPPLY_ORDER_DETAILS
CREATE UNIQUE INDEX "IDX_SUPPLY_ORDER_DETAILS_PK" ON "SUPPLY_ORDER_DETAILS" ("DETAIL_ID");

CREATE UNIQUE INDEX "IDX_PROMOTIONS_PK" ON "PROMOTIONS" ("PROMOTION_ID");

-- Indexes for CUSTOMER_PROMOTIONS
CREATE UNIQUE INDEX "IDX_CUSTOMER_PROMOTIONS_PK" ON "CUSTOMER_PROMOTIONS" ("CUSTOMER_PROMOTION_ID");

CREATE UNIQUE INDEX "IDX_REQUIRED_PARTS_PK" ON "REQUIRED_PARTS" ("SERVICE_ID", "PART_ID");

-- Indexes for STATISTICAL_REPORTS
CREATE UNIQUE INDEX "IDX_STATISTICAL_REPORTS_PK" ON "STATISTICAL_REPORTS" ("REPORT_ID");
