CREATE TABLE "REQUIRED_PARTS" (
    "SERVICE_ID" NUMBER NOT NULL ENABLE,
    "PART_ID" NUMBER NOT NULL ENABLE,
    "QUANTITY" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("SERVICE_ID", "PART_ID") USING INDEX ENABLE
);
