CREATE OR REPLACE TRIGGER trg_work_schedules_bi
BEFORE INSERT ON WORK_SCHEDULES
FOR EACH ROW
BEGIN
    IF :NEW.SCHEDULE_ID IS NULL THEN
        SELECT seq_work_schedules.NEXTVAL INTO :NEW.SCHEDULE_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_work_schedules_bi ENABLE;
