CREATE OR REPLACE TRIGGER trg_promotions_bi
BEFORE INSERT ON PROMOTIONS
FOR EACH ROW
BEGIN
    IF :NEW.PROMOTION_ID IS NULL THEN
        SELECT seq_promotions.NEXTVAL INTO :NEW.PROMOTION_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_promotions_bi ENABLE;
