CREATE OR REPLACE TRIGGER trg_employees_bi
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.EMPLOYEE_ID IS NULL THEN
        SELECT seq_employees.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_employees_bi ENABLE;
