CREATE OR REPLACE TRIGGER trg_customer_reviews_bi
BEFORE INSERT ON CUSTOMER_REVIEWS
FOR EACH ROW
BEGIN
    IF :NEW.REVIEW_ID IS NULL THEN
        SELECT seq_customer_reviews.NEXTVAL INTO :NEW.REVIEW_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_customer_reviews_bi ENABLE;
