CREATE OR REPLACE TRIGGER trg_suppliers_bi
BEFORE INSERT ON SUPPLIERS
FOR EACH ROW
BEGIN
    IF :NEW.SUPPLIER_ID IS NULL THEN
        SELECT seq_suppliers.NEXTVAL INTO :NEW.SUPPLIER_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_suppliers_bi ENABLE;
