CREATE OR REPLACE TRIGGER trg_invoices_bi
BEFORE INSERT ON INVOICES
FOR EACH ROW
BEGIN
    IF :NEW.INVOICE_ID IS NULL THEN
        SELECT seq_invoices.NEXTVAL INTO :NEW.INVOICE_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_invoices_bi ENABLE;
