CREATE OR REPLACE TRIGGER trg_statistical_reports_bi
BEFORE INSERT ON STATISTICAL_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.REPORT_ID IS NULL THEN
        SELECT seq_statistical_reports.NEXTVAL INTO :NEW.REPORT_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_statistical_reports_bi ENABLE;
