CREATE OR REPLACE TRIGGER trg_employee_roles_bi
BEFORE INSERT ON EMPLOYEE_ROLES
FOR EACH ROW
BEGIN
    IF :NEW.ROLE_ID IS NULL THEN
        SELECT seq_employee_roles.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_employee_roles_bi ENABLE;
