CREATE OR REPLACE TRIGGER trg_parts_used_bi
BEFORE INSERT ON PARTS_USED
FOR EACH ROW
BEGIN
    IF :NEW.PART_USED_ID IS NULL THEN
        SELECT seq_parts_used.NEXTVAL INTO :NEW.PART_USED_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER trg_parts_used_bi ENABLE;
